### ISSUE TITLE
0x2B73D55d49000fF43D2580Fe82d1E1Ce266aD1c4

### ISSUE THREAD

**Issue by MGmarcineczek** [maticnetwork/static#58]
0x2B73D55d49000fF43D2580Fe82d1E1Ce266aD1c4

_Originally posted by @MGmarcineczek in https://github.com/maticnetwork/static/issues/36#issuecomment-906795337_

**Comment by Seyithantas** [comment]
0x2B73D55d49000fF43D2580Fe82d1E1Ce266aD1c4
